import { themes as prismThemes } from "prism-react-renderer";
import type { Config } from "@docusaurus/types";
import type * as Preset from "@docusaurus/preset-classic";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const title = "UPrep Academic Tech Docs";
const organizationName = "jpeters-uprep";
const projectName = "uprep-academic-tech-docs";
const repoUrl = `https://github.com/${organizationName}/${projectName}`;

const config: Config = {
  title: title,
  favicon: "img/TreesLogoFavicon.png",
  trailingSlash: true,

  // Future flags, see https://docusaurus.io/docs/api/docusaurus-config#future
  future: {
    v4: true, // Improve compatibility with the upcoming Docusaurus v4
    faster: true, // @docusaurus/faster is already a dependency; this turns it on
  },

  // Set the production url of your site here
  url: "https://makers.universityprep.org/",
  // Set the /<baseUrl>/ pathname under which your site is served
  // For GitHub pages deployment, it is often '/<projectName>/'
  baseUrl: "/",

  // GitHub pages deployment config.
  // If you aren't using GitHub pages, you don't need these.
  organizationName: organizationName, // Usually your GitHub org/user name.
  projectName: projectName, // Usually your repo name.

  onBrokenLinks: "throw",
  onBrokenAnchors: "throw",
  markdown: {
    hooks: {
      onBrokenMarkdownLinks: "throw",
    },
  },

  // Even if you don't use internationalization, you can use this field to set
  // useful metadata like html lang. For example, if your site is Chinese, you
  // may want to replace "en" with "zh-Hans".
  i18n: {
    defaultLocale: "en",
    locales: ["en"],
  },

  presets: [
    [
      "classic",
      {
        docs: {
          routeBasePath: "/",
          // No sidebarPath: the sidebar is intentionally fully autogenerated
          // from the docs/ folder tree. Control labels and order with
          // _category_.json in each folder (see any docs/ subfolder for an
          // example) rather than a hand-maintained sidebars.ts.
          showLastUpdateTime: true,
          showLastUpdateAuthor: true,
          editUrl: `${repoUrl}/edit/main/website/`,
        },
        blog: false,
        theme: {
          customCss: "./src/css/custom.css",
        },
      } satisfies Preset.Options,
    ],
  ],

  themes: [
    [
      "@easyops-cn/docusaurus-search-local",
      {
        hashed: true,
        language: ["en"],
        indexDocs: true,
        indexBlog: false,
        indexPages: true,
        docsRouteBasePath: "/",
        highlightSearchTermsOnTargetPage: true,
      },
    ],
  ],

  plugins: [
    [
      "docusaurus-plugin-llms",
      {
        generateLLMsTxt: true,
        generateLLMsFullTxt: true,
        docsDir: "docs",
        title: title,
        description:
          "Academic Technology reference for UPrep students, families, faculty, and staff: Schoology, Veracross, student devices, approved software, and the Makerspaces.",
        excludeImports: true,
        removeDuplicateHeadings: true,
      },
    ],
  ],

  themeConfig: {
    colorMode: {
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: title,
      logo: {
        alt: "UPrep Tree Logo",
        src: "img/logo.png",
      },
      items: [
        {
          to: "/tech-resources",
          label: "Students & Families",
          position: "left",
        },
        {
          to: "/faculty",
          label: "Faculty",
          position: "left",
        },
        {
          to: "/software-and-vr",
          label: "Software",
          position: "left",
        },
        {
          to: "/makers",
          label: "Makers",
          position: "left",
        },
      ],
    },
    footer: {
      style: "dark",
      links: [
        {
          title: "Feedback or Questions?",
          items: [
            {
              label: "Email June",
              href: "mailto:jpeters@universityprep.org",
            },
            {
              label: "Meet with June",
              href: "https://outlook.office.com/bookwithme/user/e2af8d4993df4d598f17a7a09eeb0ee6@universityprep.org?anonymous&ismsaljsauthenabled&ep=plink",
            },
          ],
        },
        {
          title: "Links",
          items: [
            {
              label: "Schoology",
              href: "https://universityprep.schoology.com/home",
            },
            {
              label: "Veracross",
              href: "https://portals.veracross.com/uprep",
            },
            {
              label: "IT Support",
              href: "https://support.universityprep.org/",
            },
            {
              label: "GitHub",
              href: repoUrl,
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} University Prep. Site managed by June Peters, Academic Technology Program Manager.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
