import { themes as prismThemes } from "prism-react-renderer";
import type { Config } from "@docusaurus/types";
import type * as Preset from "@docusaurus/preset-classic";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const title = "UPrep Academic Tech Docs";
const organizationName = "jpeters-uprep";
const projectName = "uprep-academic-tech-docs";
const repoUrl = `https://github.com/${organizationName}/${projectName}`;

const config: Config = {
  title: title,
  favicon: "img/TreesLogoFavicon.png",
  trailingSlash: true,

  // Future flags, see https://docusaurus.io/docs/api/docusaurus-config#future
  future: {
    v4: true, // Improve compatibility with the upcoming Docusaurus v4
    faster: true, // @docusaurus/faster is already a dependency; this turns it on
  },

  // Set the production url of your site here
  url: "https://makers.universityprep.org/",
  // Set the /<baseUrl>/ pathname under which your site is served
  // For GitHub pages deployment, it is often '/<projectName>/'
  baseUrl: "/",

  // GitHub pages deployment config.
  // If you aren't using GitHub pages, you don't need these.
  organizationName: organizationName, // Usually your GitHub org/user name.
  projectName: projectName, // Usually your repo name.

  onBrokenLinks: "throw",
  onBrokenAnchors: "throw",
  markdown: {
    hooks: {
      onBrokenMarkdownLinks: "throw",
    },
  },

  // Even if you don't use internationalization, you can use this field to set
  // useful metadata like html lang. For example, if your site is Chinese, you
  // may want to replace "en" with "zh-Hans".
  i18n: {
    defaultLocale: "en",
    locales: ["en"],
  },

  presets: [
    [
      "classic",
      {
        docs: {
          routeBasePath: "/",
          // No sidebarPath: the sidebar is intentionally fully autogenerated
          // from the docs/ folder tree. Control labels and order with
          // _category_.json in each folder (see any docs/ subfolder for an
          // example) rather than a hand-maintained sidebars.ts.
          showLastUpdateTime: true,
          showLastUpdateAuthor: true,
          editUrl: `${repoUrl}/edit/main/website/`,
        },
        blog: false,
        theme: {
          customCss: "./src/css/custom.css",
        },
      } satisfies Preset.Options,
    ],
  ],

  themes: [
    [
      "@easyops-cn/docusaurus-search-local",
      {
        hashed: true,
        language: ["en"],
        indexDocs: true,
        indexBlog: false,
        indexPages: true,
        docsRouteBasePath: "/",
        highlightSearchTermsOnTargetPage: true,
      },
    ],
  ],

  plugins: [
    [
      "docusaurus-plugin-llms",
      {
        generateLLMsTxt: true,
        generateLLMsFullTxt: true,
        docsDir: "docs",
        title: title,
        description:
          "Academic Technology reference for UPrep students, families, faculty, and staff: Schoology, Veracross, student devices, approved software, and the Makerspaces.",
        excludeImports: true,
        removeDuplicateHeadings: true,
      },
    ],
    [
      "@docusaurus/plugin-client-redirects",
      {
        // Every path moved or removed by the Part B audience-first IA
        // restructure, plus Part C's Schoology section restructure. These are
        // linked from emails, Schoology courses, and the Veracross portal, so
        // old links must keep working.
        redirects: [
          {
            from: "/faculty/schoology/rubrics",
            to: "/faculty/schoology/best-practices/rubrics",
          },
          {
            from: "/faculty/schoology/course-headers",
            to: "/faculty/schoology/best-practices/course-headers",
          },
          {
            from: "/faculty/schoology/working-in-resources",
            to: "/faculty/schoology/best-practices/reusing-your-materials/working-in-resources",
          },
          {
            from: "/faculty/schoology/saving-to-resources",
            to: "/faculty/schoology/best-practices/reusing-your-materials/saving-to-resources",
          },
          {
            from: "/faculty/schoology/adding-resources-to-a-course",
            to: "/faculty/schoology/best-practices/reusing-your-materials/adding-resources-to-a-course",
          },
          {
            from: "/faculty/schoology/student-centered-courses",
            to: "/faculty/schoology/requirements",
          },
          {
            from: "/faculty/schoology/issues",
            to: "/faculty/schoology/faq",
          },
          {
            from: "/faculty/schoology/issues/access",
            to: "/faculty/schoology/faq/access",
          },
          {
            from: "/faculty/schoology/issues/accessing-archived-courses",
            to: "/faculty/schoology/faq/accessing-archived-courses",
          },
          {
            from: "/faculty/schoology/issues/add-section",
            to: "/faculty/schoology/faq/add-section",
          },
          {
            from: "/faculty/schoology/issues/adding-dropping-students",
            to: "/faculty/schoology/faq/adding-dropping-students",
          },
          {
            from: "/faculty/schoology/issues/advisor-dashboard",
            to: "/faculty/schoology/faq/advisor-dashboard",
          },
          {
            from: "/faculty/schoology/issues/become-course-admin",
            to: "/faculty/schoology/faq/become-course-admin",
          },
          {
            from: "/faculty/schoology/issues/course-missing",
            to: "/faculty/schoology/faq/course-missing",
          },
          {
            from: "/faculty/schoology/issues/extend-course-through-summer",
            to: "/faculty/schoology/faq/extend-course-through-summer",
          },
          {
            from: "/faculty/schoology/issues/reorder-courses",
            to: "/faculty/schoology/faq/reorder-courses",
          },
          {
            from: "/faculty/schoology/issues/schoology-manager",
            to: "/faculty/schoology/faq/schoology-manager",
          },
          {
            from: "/tech-resources",
            to: "/families",
          },
          {
            from: "/tech-resources/chromebook-access-control",
            to: "/families/chromebook-access-control",
          },
          {
            from: "/tech-resources/schoology-overview",
            to: "/families/schoology-for-families",
          },
          {
            from: "/tech-resources/student-laptops",
            to: "/families",
          },
          {
            from: "/tech-resources/student-laptops/middle-school-chromebooks",
            to: "/families/middle-school-chromebooks",
          },
          {
            from: "/tech-resources/student-laptops/chromebook-setup",
            to: "/families/chromebook-setup",
          },
          {
            from: "/tech-resources/student-laptops/upper-school-laptops",
            to: "/families/upper-school-laptops",
          },
          {
            from: "/tech-resources/student-laptops/upper-school-laptop-setup",
            to: "/families/upper-school-laptop-setup",
          },
          {
            from: "/tech-resources/student-laptops/faq",
            to: "/families/faq",
          },
          {
            from: "/tech-resources/student-laptops/faq/family-link-school-account",
            to: "/families/parental-controls/family-link-school-account",
          },
          {
            from: "/tech-resources/student-laptops/faq/parental-control-apps",
            to: "/families/parental-controls/parental-control-apps",
          },
          {
            from: "/tech-resources/student-laptops/faq/backup-pc",
            to: "/families/faq/backup-pc",
          },
          {
            from: "/tech-resources/student-laptops/faq/chromebooks-us",
            to: "/families/faq/chromebooks-us",
          },
          {
            from: "/tech-resources/student-laptops/faq/how-to-print",
            to: "/families/faq/how-to-print",
          },
          {
            from: "/tech-resources/student-laptops/faq/macbook-neo",
            to: "/families/faq/macbook-neo",
          },
          {
            from: "/tech-resources/student-laptops/faq/password-change",
            to: "/families/faq/password-change",
          },
          {
            from: "/tech-resources/student-laptops/faq/wifi-connection",
            to: "/families/faq/wifi-connection",
          },
          {
            from: "/tech-resources/technology-use-guidelines",
            to: "/policies/technology-use-guidelines",
          },
          {
            from: "/tech-resources/privacy-and-coppa",
            to: "/policies/privacy-and-coppa",
          },
          {
            from: "/software-and-vr",
            to: "/software",
          },
          {
            from: "/software-and-vr/fully-supported-software",
            to: "/software/fully-supported",
          },
          {
            from: "/software-and-vr/fully-supported-software/adobe-creative-cloud",
            to: "/software/fully-supported/adobe-creative-cloud",
          },
          {
            from: "/software-and-vr/fully-supported-software/autodesk",
            to: "/software/fully-supported/autodesk",
          },
          {
            from: "/software-and-vr/recommended-free-software",
            to: "/software/recommended-free",
          },
          {
            from: "/software-and-vr/unsupported-software",
            to: "/software/unsupported",
          },
          {
            from: "/software-and-vr/it-supported-software",
            to: "/software/it-supported",
          },
          {
            from: "/software-and-vr/vr-software",
            to: "/software/vr",
          },
          {
            from: "/it-support",
            to: "/about/it-support",
          },
          {
            from: "/accessibility",
            to: "/students/accessibility-tools",
          },
        ],
      },
    ],
  ],

  themeConfig: {
    colorMode: {
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: title,
      logo: {
        alt: "UPrep Tree Logo",
        src: "img/logo.png",
      },
      items: [
        {
          to: "/students",
          label: "Students",
          position: "left",
        },
        {
          to: "/families",
          label: "Families",
          position: "left",
        },
        {
          to: "/faculty",
          label: "Faculty",
          position: "left",
        },
        {
          to: "/software",
          label: "Software",
          position: "left",
        },
        {
          to: "/makers",
          label: "Makers",
          position: "left",
        },
      ],
    },
    footer: {
      style: "dark",
      links: [
        {
          title: "Feedback or Questions?",
          items: [
            {
              label: "Email June",
              href: "mailto:jpeters@universityprep.org",
            },
            {
              label: "Meet with June",
              href: "https://outlook.office.com/bookwithme/user/e2af8d4993df4d598f17a7a09eeb0ee6@universityprep.org?anonymous&ismsaljsauthenabled&ep=plink",
            },
          ],
        },
        {
          title: "Links",
          items: [
            {
              label: "Schoology",
              href: "https://universityprep.schoology.com/home",
            },
            {
              label: "Veracross",
              href: "https://portals.veracross.com/uprep",
            },
            {
              label: "IT Support",
              href: "https://support.universityprep.org/",
            },
            {
              label: "GitHub",
              href: repoUrl,
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} University Prep. Site managed by June Peters, Academic Technology Program Manager.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
